# Generated by Django 5.2.6 on 2025-10-24 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('type_sinistre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('clos', 'Clos'), ('refuse', 'Refusé')], default='en_cours', max_length=20)),
                ('montant_demande', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_indemnisation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
