# Generated by Django 5.2.6 on 2025-11-01 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sinistre',
            options={'ordering': ['-date_declaration'], 'verbose_name': 'Sinistre', 'verbose_name_plural': 'Sinistres'},
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to=settings.AUTH_USER_MODEL, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='date_declaration',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de déclaration'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='description',
            field=models.TextField(help_text='Décrivez les circonstances du sinistre', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='montant_demande',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant demandé'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='montant_indemnisation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Montant d'indemnisation"),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('clos', 'Clos'), ('refuse', 'Refusé')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='sinistre',
            name='type_sinistre',
            field=models.CharField(choices=[('automobile', 'Automobile'), ('habitation', 'Habitation'), ('sante', 'Santé'), ('autre', 'Autre')], max_length=20, verbose_name='Type de sinistre'),
        ),
    ]
