# Generated by Django 5.2.6 on 2025-11-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0002_alter_sinistre_options_alter_sinistre_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='titre',
            field=models.CharField(default='Sinistre sans titre', help_text='Ex: Dégât des eaux - Appartement Tunis', max_length=200, verbose_name='Titre'),
            preserve_default=False,
        ),
    ]
