# Generated by Django 5.2.6 on 2025-11-01 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0003_sinistre_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinistre',
            name='date_declaration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de déclaration'),
        ),
    ]
