# Generated by Django 5.2.6 on 2025-11-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0004_alter_sinistre_date_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sinistre',
            name='justificatif',
            field=models.FileField(blank=True, null=True, upload_to='sinistres/', verbose_name='Justificatif'),
        ),
    ]
