"""
Django settings for assurmaghrebia project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-v-qn30)w^!3z#2=!c!%56#xa9wy*j*=ki=u0oifl(%+3(69z#^'
DEBUG = True
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'jazzmin',  
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'espace_client.apps.EspaceClientConfig', 
    'sinistre',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'assurmaghrebia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'assurmaghrebia.wsgi.application'

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'fr'
TIME_ZONE = 'Africa/Tunis'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Authentication redirects
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========================================
# 🎨 CONFIGURATION JAZZMIN (Admin moderne)
# ========================================
JAZZMIN_SETTINGS = {
    # Titre de l'application
    "site_title": "AssurMaghrebia Admin",
    "site_header": "AssurMaghrebia",
    "site_brand": "AssurMaghrebia",
    "welcome_sign": "Bienvenue sur l'administration AssurMaghrebia",
    "copyright": "AssurMaghrebia 2025",
    
    # Recherche
    "search_model": ["auth.User", "sinistre.Sinistre"],
    
    # Menu
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index"},
        {"name": "Voir le site", "url": "/", "new_window": True},
    ],
    
    # Options d'affichage
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Ordre des applications
    "order_with_respect_to": ["auth", "espace_client", "sinistre"],
    
    # Icônes pour vos modèles
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "espace_client.ClientMaghrebia": "fas fa-user-circle",
        "espace_client.PoliceMaghrebia": "fas fa-file-contract",
        "espace_client.SinistreMaghrebia": "fas fa-exclamation-triangle",
        "sinistre.Sinistre": "fas fa-file-medical-alt",
    },
    
    # Thème (options: default, darkly, flatly, solar, superhero, etc.)
    "theme": "flatly",
    
    # Format des formulaires
    "changeform_format": "horizontal_tabs",
}

# Options UI
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    "dark_mode_theme": None,
}
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuration Email pour réinitialisation de mot de passe
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # ou votre serveur SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'chaayma.tlatli@gmail.com'  # Votre email
EMAIL_HOST_PASSWORD = 'CHchchch123'  # Mot de passe d'application Gmail
DEFAULT_FROM_EMAIL = 'AssurMaghrebia <chaayma.tlatli@gmail.com>'

# URL de réinitialisation (pour les emails)
PASSWORD_RESET_TIMEOUT = 3600  # 1 heure (en secondes)
# Mode développement : affiche les emails dans la console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'