# Generated by Django 5.2.6 on 2025-11-01 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMaghrebia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8, unique=True, verbose_name='CIN')),
                ('telephone', models.CharField(max_length=12)),
                ('adresse', models.TextField()),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceMaghrebia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(max_length=20, unique=True)),
                ('type_assurance', models.CharField(choices=[('auto', 'Assurance Auto (RC + Tous Risques)'), ('sante', 'Assurance Santé (Médiplus, etc.)'), ('habitation', 'Assurance Habitation'), ('voyage', 'Assurance Voyage')], max_length=20)),
                ('date_effet', models.DateField()),
                ('date_expiration', models.DateField()),
                ('prime_mensuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espace_client.clientmaghrebia')),
            ],
        ),
        migrations.CreateModel(
            name='SinistreMaghrebia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sinistre', models.DateField()),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_investigation', 'En investigation'), ('expertise_en_cours', 'Expertise en cours'), ('indemnise', 'Indemnisé'), ('rejete', 'Rejeté')], default='nouveau', max_length=20)),
                ('montant_indemnite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_traitement', models.DateField(blank=True, null=True)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='espace_client.policemaghrebia')),
            ],
        ),
    ]
