# Generated by Django 5.2.6 on 2025-11-06 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espace_client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmaghrebia',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='policemaghrebia',
            options={'verbose_name': 'Police', 'verbose_name_plural': 'Polices'},
        ),
        migrations.AlterModelOptions(
            name='sinistremaghrebia',
            options={'verbose_name': 'Sinistre', 'verbose_name_plural': 'Sinistres'},
        ),
        migrations.AlterField(
            model_name='clientmaghrebia',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='clientmaghrebia',
            name='date_inscription',
            field=models.DateField(auto_now_add=True, verbose_name="Date d'inscription"),
        ),
        migrations.AlterField(
            model_name='clientmaghrebia',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='clientmaghrebia',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polices', to='espace_client.clientmaghrebia'),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='date_effet',
            field=models.DateField(verbose_name="Date d'effet"),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='est_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='numero_police',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numéro de police'),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='prime_mensuelle',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prime mensuelle'),
        ),
        migrations.AlterField(
            model_name='policemaghrebia',
            name='type_assurance',
            field=models.CharField(choices=[('auto', 'Assurance Auto (RC + Tous Risques)'), ('sante', 'Assurance Santé (Médiplus, etc.)'), ('habitation', 'Assurance Habitation'), ('voyage', 'Assurance Voyage')], max_length=20, verbose_name="Type d'assurance"),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='date_sinistre',
            field=models.DateField(verbose_name='Date du sinistre'),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='date_traitement',
            field=models.DateField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='lieu',
            field=models.CharField(max_length=200, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='montant_indemnite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Montant de l'indemnité"),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='police',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sinistres', to='espace_client.policemaghrebia'),
        ),
        migrations.AlterField(
            model_name='sinistremaghrebia',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_investigation', 'En investigation'), ('expertise_en_cours', 'Expertise en cours'), ('indemnise', 'Indemnisé'), ('rejete', 'Rejeté')], default='nouveau', max_length=20, verbose_name='Statut'),
        ),
    ]
